# Generated by Django 2.1.3 on 2018-11-07 17:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('water', models.CharField(max_length=2)),
                ('times', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_name', models.CharField(max_length=20)),
                ('goods_id', models.CharField(max_length=21)),
                ('goods_stock', models.CharField(max_length=99)),
                ('goods_address', models.CharField(max_length=40)),
                ('user_home', models.CharField(max_length=40)),
                ('address_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('yes_goods', models.CharField(default='未收货', max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='goods',
            name='goods_address',
            field=models.CharField(default='北京', max_length=40),
        ),
        migrations.AddField(
            model_name='users',
            name='user_home',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='order',
            name='order_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sop.Users'),
        ),
    ]
