# Generated by Django 2.1.3 on 2018-11-14 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sop', '0002_order_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_details', models.CharField(max_length=500)),
                ('goods_lyric', models.CharField(max_length=500)),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sop.Goods')),
            ],
        ),
    ]
