# Generated by Django 2.1.3 on 2018-11-14 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sop', '0003_goodsdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='goods_music',
            field=models.CharField(default='', max_length=200),
        ),
    ]
