# Generated by Django 2.1.2 on 2018-10-16 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_name', models.CharField(max_length=10)),
                ('stu_age', models.CharField(max_length=10)),
                ('stu_class', models.CharField(max_length=10)),
            ],
        ),
    ]
