# Generated by Django 2.1.2 on 2018-10-17 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stus', '0002_home'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='stu_class',
            new_name='stu_password',
        ),
    ]
